# Generated by Django 5.2.4 on 2025-10-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='button_work',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vips',
            name='buyed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
