# Generated by Django 5.2.4 on 2025-10-04 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_money', '0002_alter_button_button_work_alter_vips_buyed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='button',
            old_name='button_work',
            new_name='next_roll',
        ),
        migrations.AlterField(
            model_name='button',
            name='button_clicked',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2025, 10, 4, 18, 37, 20, 241443)),
        ),
        migrations.AlterField(
            model_name='vips',
            name='buyed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vips',
            name='working_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
