# Generated by Django 5.2.4 on 2025-10-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_money', '0003_rename_button_work_button_next_roll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='button_clicked',
        ),
    ]
