# Generated by Django 5.2.4 on 2025-11-08 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_money', '0004_remove_button_button_clicked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vips',
            name='working_date',
        ),
        migrations.AddField(
            model_name='vips',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='vips',
            name='payer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vips',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vips',
            name='status',
            field=models.CharField(default='created', max_length=50),
        ),
        migrations.AddField(
            model_name='vips',
            name='works_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 8, 23, 14, 25, 758796)),
        ),
    ]
