# Generated by Django 5.2.4 on 2025-11-11 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_money', '0005_remove_vips_working_date_vips_amount_vips_payer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vips',
            name='works_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 11, 16, 4, 11, 579615)),
        ),
    ]
