# Generated by Django 5.2.4 on 2025-08-13 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_posts_sell', '0002_sell_post_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell_post',
            name='Category',
        ),
    ]
