# Generated by Django 5.2.4 on 2025-08-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_posts_sell', '0003_remove_sell_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_post',
            name='Post_status',
            field=models.IntegerField(choices=[(1, 'pending_review'), (2, 'to edit'), (3, 'approved')], default=1),
        ),
    ]
