# Generated by Django 5.2.4 on 2025-08-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_posts_sell', '0004_alter_sell_post_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_post',
            name='Add_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
