# Generated by Django 5.2.4 on 2025-08-21 14:34

import forum_posts_sell.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_posts_sell', '0004_alter_sell_post_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_post',
            name='Post_life',
            field=models.DateField(default=forum_posts_sell.models.get_post_life),
        ),
    ]
