# Generated by Django 5.2.4 on 2025-08-24 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_posts_sell', '0005_sell_post_post_life'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyed_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(default='', max_length=5000)),
                ('foring_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_posts_sell.sell_post')),
            ],
        ),
    ]
