# Generated by Django 5.2.4 on 2025-08-24 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_posts_sell', '0006_buyed_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_date', models.DateTimeField(auto_now_add=True)),
                ('Rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('foring_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_posts_sell.sell_post')),
            ],
        ),
        migrations.CreateModel(
            name='user_bought_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('foring_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_posts_sell.sell_post')),
            ],
        ),
    ]
