# Generated by Django 5.2.4 on 2025-08-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_posts_sell', '0007_opinion_user_bought_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='foring_key',
            new_name='foring_key_buy_item',
        ),
        migrations.RenameField(
            model_name='user_bought_items',
            old_name='foring_key',
            new_name='foring_key_buy_item',
        ),
    ]
