# Generated by Django 5.2.4 on 2025-08-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_posts_sell', '0008_rename_foring_key_opinion_foring_key_buy_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyed_item',
            old_name='foring_key',
            new_name='foring_key_sell_post',
        ),
    ]
