# Generated by Django 5.2.4 on 2025-09-11 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_posts_sell', '0009_rename_foring_key_buyed_item_foring_key_sell_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_bought_items',
            name='foring_key_buy_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_posts_sell.buyed_item'),
        ),
    ]
