# Generated by Django 5.2.4 on 2025-11-11 14:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_register', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='key',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='User_gen_kay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_created', models.DateTimeField(default=datetime.datetime(2025, 11, 11, 15, 8, 40, 496793))),
                ('nex_key', models.DateTimeField(default=datetime.datetime(2025, 12, 11, 15, 8, 40, 497528))),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_register.keys')),
            ],
        ),
    ]
