# Generated by Django 5.2.4 on 2025-11-11 15:04

import datetime
import django.db.models.deletion
import forum_register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_register', '0002_alter_keys_key_user_gen_kay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_gen_kay',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum_register.keys'),
        ),
        migrations.AlterField(
            model_name='user_gen_kay',
            name='key_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user_gen_kay',
            name='nex_key',
            field=models.DateTimeField(default=forum_register.models.works_until_default),
        ),
    ]
