# Generated by Django 5.2.4 on 2025-08-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_money',
            field=models.IntegerField(default=0),
        ),
    ]
