# Generated by Django 5.2.4 on 2025-10-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_users', '0002_customuser_user_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'VIP'), (3, 'Super VIP'), (4, 'Moderator'), (5, 'Head_Moderator')], default=1),
        ),
    ]
