# Generated by Django 5.2.4 on 2025-11-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_users', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'VIP'), (3, 'Super_VIP'), (4, 'Moderator'), (5, 'Head_Moderator')], default=1),
        ),
    ]
