# Generated by Django 5.2.4 on 2025-08-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='Tags',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Titles',
            new_name='Title',
        ),
    ]
