# Generated by Django 5.2.4 on 2025-08-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_posts', '0002_rename_tags_post_tags_rename_titles_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Tags',
            new_name='tags',
        ),
    ]
