# Generated by Django 5.2.4 on 2025-08-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_posts', '0003_rename_tags_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Post_status',
            field=models.CharField(choices=[(1, 'pending_review'), (2, 'to edit'), (3, 'approved')], default=1),
        ),
    ]
